site_name: David Lab FoodSeq Handbook

nav:
- Getting Started:
  - Home: index.md
  # - Introduction to Lab Biostatistics: intro.md
  - Setting Up: settingup.md
- Wet Lab Protocols:
  - Overview: wetlab.md
  - DNA Extraction: extraction.md
  - PCR Amplification: pcr.md
  - Gel Electrophoresis: gel.md
  - Amplicon Cleaning: cleaning.md
  - Quantification and Pooling: pooling.md
  - Sequencing: sequencing.md
- Creating a Phyloseq:
  - Creating a Phyloseq (trnL and 12Sv5): pipeline.md
  - Creating a Phyloseq (16S): 16s.md
  - Creating the References: references.md
  - Creating the SQL File: sql.md
- Post-Phyloseq Processing and Analysis:
  - Overview: processing.md
  - Calculating Diversity: diversity.md
  - Calculating Relative Abundance: abundance.md
  - Creating a PCA Plot: pca.md
  - Assigning Common Names: commonnames.md
  - Anonymizing Human Reads: anonymizer.md

theme:
  name: material
  features:
    - header.autohide
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.top
    - navigation.instant
    - navigation.footer
    - toc.integrate
    - content.code.copy
    - content.code.select
    - search.suggest
    - content.tabs.link
  font:
    text: Source Sans Pro
    code: IBM Plex Mono
  palette:
        # Palette toggle for dark mode
    - scheme: default
      primary: white
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: custom
      toggle:
        icon: material/weather-night
        name: Switch to light mode

repo_url: https://github.com/LAD-LAB
repo_name: LAD-LAB

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - git-authors
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: false
  - offline

extra:
  generator: true
  analytics:
    provider: google
    property: G-1LM4D2NZZL
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            <a href="https://github.com/LAD-LAB/lad-lab.github.io/issues/new/?title=[Feedback]+{title}&body=Page:+{url}%0A%0AFeedback:+" target="_blank" rel="noopener">opening an issue</a>.